squash! dt-bindings: gpio: add starfive,jh7100-gpio bindings
make dt_binding_check DT_SCHEMA_FILES=Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml:

    Error: Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.example.dts:24.31-32 syntax error
    FATAL ERROR: Unable to parse input tree

Fix clock ID and add missing semicolon.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>