perf list: Cast strstr() result to allow writing to temp list memory
In print_symbol_events(), 'nd->s' is 'const char *' so strstr()
returns 'const char *' with newer gcc/glibc, but the code needs to
temporarily write '\0' to split the alias string.

The memory is owned by a temporary strlist created for listing and
deleted at the end of the function, so writing to it is safe.
Cast the result to (char *) to silence the -Werror=discarded-qualifiers
error with gcc-15.

Fixes build failure:
  util/print-events.c:269:31: error: initialization discards 'const'
  qualifier from pointer target type [-Werror=discarded-qualifiers]
    269 |                 char *alias = strstr(nd->s, " OR ");

Change-Id: Ibf8c4ea7bd7a0d8352602ac91f9a4cd86eba8b8a
Signed-off-by: lijuan <juan.li@spacemit.com>