perf riscv: Constify variables storing the result of strrchr() on const string
In _get_field(), the parameter 'line' is 'const char *', so the return
value of strrchr(line, ...) must be stored in 'const char *' variables
to avoid -Werror=discarded-qualifiers with newer gcc/glibc.

Fixes build failure with gcc-15:
  arch/riscv/util/header.c:24:9: error: assignment discards 'const'
  qualifier from pointer target type [-Werror=discarded-qualifiers]
    24 |         line2 = strrchr(line, ' ');

Change-Id: I593d875bdf726a6e986b0282d9d49443f60cbc11
Signed-off-by: lijuan <juan.li@spacemit.com>